version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      cloudflare:
        applies-to: version-updates
        patterns:
          - "@cloudflare/*"
          - "wrangler"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"