name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm install
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.7.3 # Should match version in package.json
      - name: Run Biome
        run: biome ci .
      - run: npm run test